### ISSUE TITLE
Cannot install on Windows, fresh env, clean install

### ISSUE THREAD

**Issue by Vaspra** [Poissonfish/GRID#12]
**Describe the bug**
Installing using conda on Windows is resulting in an error consistently on different machines. I believe its due to a mix of conda-forge and pypi packages. After installation, running grid results in:

```
(grid) C:\WINDOWS\system32>python -m grid
~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
                 Welcome to GRID Ver.1.2.18
~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
Author      : James Chen <chun-peng.chen@wsu.edu>
Last update : Aug 31, 2021
User manual : https://poissonfish.github.io/GRID/
~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
Recent update
    - Support images with huge dimensions (> 32767)
    - Add CRS to shapefiles (.prj)
    - Support ESRI shapefile compatible in QGIS
~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\grid\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\Anaconda3\envs\grid\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\Anaconda3\envs\grid\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\Anaconda3\envs\grid\lib\site-packages\grid\__init__.py", line 72, in <module>
    from .grid import *
  File "C:\ProgramData\Anaconda3\envs\grid\lib\site-packages\grid\grid.py", line 4, in <module>
    from .gmap import *
  File "C:\ProgramData\Anaconda3\envs\grid\lib\site-packages\grid\gmap.py", line 7, in <module>
    from .io import *
  File "C:\ProgramData\Anaconda3\envs\grid\lib\site-packages\grid\io.py", line 12, in <module>
    import rasterio
  File "C:\ProgramData\Anaconda3\envs\grid\lib\site-packages\rasterio\__init__.py", line 13, in <module>
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
ImportError: DLL load failed while importing _version: The specified procedure could not be found.
```

**To Reproduce**
1. New env, `conda create -n name python=3.8`
2. `conda config --add channels conda-forge`
3. (tried with and without) `conda config --set channel_priority strict`
4. `conda activate name`
5. `conda install rasterio`
6. `pip install photo_grid`
7. `python -m grid`

**Expected behavior**
App loads normally.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Typical Windows 10 Anaconda install

**Comment by Poissonfish** [comment]
Hi, thanks for the feedback. I have added instructions for Windows users here: https://poissonfish.github.io/GRID/ch1_started/installation.html#step-2-rasterio-windows-users

It works on my Windows machine. Please let me know if this solution resolves your issue.  

Thanks,
James
