### ISSUE TITLE
PyQt6 Error

### ISSUE THREAD

**Issue by kieranatkins** [Poissonfish/GRID#19]
**Describe the bug**
Program loads correctly, when loading a tiff program errors out with the following message:
```
C:\Users\phenomics\anaconda3\envs\grid\lib\site-packages\grid\__main__.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
QLayout::removeWidget: Cannot remove a null widget.
Traceback (most recent call last):
  File "C:\Users\phenomics\anaconda3\envs\grid\lib\site-packages\grid\gridGUI.py", line 118, in <lambda>
    self.btNext.clicked.connect(lambda: self.showCropper())
  File "C:\Users\phenomics\anaconda3\envs\grid\lib\site-packages\grid\gridGUI.py", line 130, in showCropper
    self.updateMainPn(panel=Panels.CROPPER, isNew=isNew)
  File "C:\Users\phenomics\anaconda3\envs\grid\lib\site-packages\grid\gridGUI.py", line 187, in updateMainPn
    msg.exec_()
AttributeError: 'QMessageBox' object has no attribute 'exec_'. Did you mean: 'exec'?
```
**To Reproduce**
python -m grid
applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Versions: photo_grid==1.3.11, python==3.10.13, gdal 3.4.3 (conda-forge). rasterio 1.4.2 (conda-forge)

**Additional context**
It seems PyQt6 changed the `exec_` command to be just `exec`? I don't know if this is reflected in the latest version of grid? Any help appreciated. Thanks.

**Comment by Poissonfish** [comment]
Hi @kieranatkins, thank you for your report. I just pushed the fix to the latest version v1.3.13. You should be prompted for the update automatically when you open GRID next time. Please help check if the issue persists. Thank you!!

**Comment by kieranatkins** [comment]
Hi @Poissonfish, sorry for the slow response but that all seems to be working now. Thank you for the swift fix!
